apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: mariadb-snapshot
spec:
  volumeSnapshotClassName: pure-snapshotclass
  source:
    persistentVolumeClaimName: data-wordpress-mariadb-0
