apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: mariadb-snapshot
spec:
  snapshotClassName: pure-snapshotclass
  source:
    name: data-wordpress-mariadb-0
    kind: PersistentVolumeClaim
