apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: fio-snapshot
spec:
  snapshotClassName: pure-snapshotclass
  source:
    name: dbench-pv-claim-block
    kind: PersistentVolumeClaim
