kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim-file
spec:
  storageClassName: pure-file
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Gi 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-file
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: dnix101/dbench:latest
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          - name: FIO_SIZE
            value: 500G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-pv-claim-file
  backoffLimit: 4
